version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: gatcha-project-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
      - mongo_data:/data/db

  auth-api:
    build: ./auth-api
    container_name: gatcha-project-auth-api
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

  player-api:
    build: ./player-api
    container_name: gatcha-project-player-api
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

  monsters-api:
    build: ./monsters-api
    container_name: gatcha-project-monsters-api
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

  invocation-api:
    build: ./invocation-api
    container_name: gatcha-project-invocation-api
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

volumes:
  mongo_data:
